version: '3.7'
services:
  mysql:
    image: mysql:latest
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=app
      - MYSQL_USER=app
      - MYSQL_PASSWORD=pass
    ports:
      - '3306:3306'

  postgres:
    image: postgres:12-alpine
    environment:
      - POSTGRES_USER=app
      - POSTGRES_DB=app
      - POSTGRES__PASSWORD=pass
    ports:
      - '5432:5432'

  node-app:
    build: ./gate-simulator
    image: node-app:1.0
    ports:
      - '9999:9999'